// Strings.Designer.cs (generated-like content)
namespace WordsGame
{
    using System;
    using System.Resources;
    using System.Globalization;

    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("proj1rev3.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the base word (8–30 characters): .
        /// </summary>
        internal static string msgEnterWord
        {
            get
            {
                return ResourceManager.GetString("msgEnterWord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The word must be between 8 and 30 letters!.
        /// </summary>
        internal static string msgTooShort
        {
            get
            {
                return ResourceManager.GetString("msgTooShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Let’s start the game!.
        /// </summary>
        internal static string msgGameStart
        {
            get
            {
                return ResourceManager.GetString("msgGameStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Player {0}: (10 seconds).
        /// </summary>
        internal static string msgPlayerTurn
        {
            get
            {
                return ResourceManager.GetString("msgPlayerTurn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time’s up! Player {0} missed the turn and lost!.
        /// </summary>
        internal static string msgLoseTimeout
        {
            get
            {
                return ResourceManager.GetString("msgLoseTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This word has already been used!.
        /// </summary>
        internal static string msgUsed
        {
            get
            {
                return ResourceManager.GetString("msgUsed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can’t make this word from the base word!.
        /// </summary>
        internal static string msgInvalid
        {
            get
            {
                return ResourceManager.GetString("msgInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Game over..
        /// </summary>
        internal static string msgEnd
        {
            get
            {
                return ResourceManager.GetString("msgEnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empty input — enter a word again..
        /// </summary>
        internal static string msgEmpty
        {
            get
            {
                return ResourceManager.GetString("msgEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The word must contain only letters of the English alphabet!.
        /// </summary>
        internal static string msgWrongAlphabet
        {
            get
            {
                return ResourceManager.GetString("msgWrongAlphabet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press Enter to exit....
        /// </summary>
        internal static string msgPressEnter
        {
            get
            {
                return ResourceManager.GetString("msgPressEnter", resourceCulture);
            }
        }
    }
}